const std = @import("std");
const InputStream = @import("inputStream.zig").InputStream;

const LexerStates = enum {
    Data,
    RCDATA,
    RAWTEXT,
    Scriptdata,
    PLAINTEXT,
    Tagopen,
    Endtagopen,
    Tagname,
    RCDATAlessthansign,
    RCDATAendtagopen,
    RCDATAendtagname,
    RAWTEXTlessthansign,
    RAWTEXTendtagopen,
    RAWTEXTendtagname,
    Scriptdatalessthansign,
    Scriptdataendtagopen,
    Scriptdataendtagname,
    Scriptdataescapestart,
    Scriptdataescapestartdash,
    Scriptdataescaped,
    Scriptdataescapeddash,
    Scriptdataescapeddashdash,
    Scriptdataescapedlessthansign,
    Scriptdataescapedendtagopen,
    Scriptdataescapedendtagname,
    Scriptdatadoubleescapestart,
    Scriptdatadoubleescaped,
    Scriptdatadoubleescapeddash,
    Scriptdatadoubleescapeddashdash,
    Scriptdatadoubleescapedlessthansign,
    Scriptdatadoubleescapeend,
    Beforeattributename,
    Attributename,
    Afterattributename,
    Beforeattributevalue,
    Attributevaluedoublequoted,
    Attributevaluesinglequoted,
    Attributevalueunquoted,
    Afterattributevaluequoted,
    Selfclosingstarttag,
    Boguscomment,
    Markupdeclarationopen,
    Commentstart,
    Commentstartdash,
    Comment,
    Commentlessthansign,
    Commentlessthansignbang,
    Commentlessthansignbangdash,
    Commentlessthansignbangdashdash,
    Commentenddash,
    Commentend,
    Commentendbang,
    DOCTYPE,
    BeforeDOCTYPEname,
    DOCTYPEname,
    AfterDOCTYPEname,
    AfterDOCTYPEpublickeyword,
    BeforeDOCTYPEpublicidentifier,
    DOCTYPEpublicidentifierdoublequoted,
    DOCTYPEpublicidentifiersinglequoted,
    AfterDOCTYPEpublicidentifier,
    BetweenDOCTYPEpublicandsystemidentifiers,
    AfterDOCTYPEsystemkeyword,
    BeforeDOCTYPEsystemidentifier,
    DOCTYPEsystemidentifierdoublequoted,
    DOCTYPEsystemidentifiersinglequoted,
    AfterDOCTYPEsystemidentifier,
    BogusDOCTYPE,
    CDATAsection,
    CDATAsectionbracket,
    CDATAsectionend,
    Characterreference,
    Namedcharacterreference,
    Ambiguousampersand,
    Numericcharacterreference,
    Hexadecimalcharacterreferencestart,
    Decimalcharacterreferencestart,
    Hexadecimalcharacterreference,
    Decimalcharacterreference,
    Numericcharacterreferenceend,
};

const HtmlLexer = struct {
    stream: InputStream,
    allocator: std.mem.Allocator,
    state: LexerStates = .Data,

    fn init(allocator: std.mem.Allocator, input_stream: InputStream) HtmlLexer {
        return .{ .stream = input_stream, .allocator = allocator };
    }

    fn run(lexer: *HtmlLexer) void {
        sw: switch (lexer.state) {
            .Data => {},
            .RCDATA => {},
            .RAWTEXT => {},
            .Scriptdata => {},
            .PLAINTEXT => {},
            .Tagopen => {},
            .Endtagopen => {},
            .Tagname => {},
            .RCDATAlessthansign => {},
            .RCDATAendtagopen => {},
            .RCDATAendtagname => {},
            .RAWTEXTlessthansign => {},
            .RAWTEXTendtagopen => {},
            .RAWTEXTendtagname => {},
            .Scriptdatalessthansign => {},
            .Scriptdataendtagopen => {},
            .Scriptdataendtagname => {},
            .Scriptdataescapestart => {},
            .Scriptdataescapestartdash => {},
            .Scriptdataescaped => {},
            .Scriptdataescapeddash => {},
            .Scriptdataescapeddashdash => {},
            .Scriptdataescapedlessthansign => {},
            .Scriptdataescapedendtagopen => {},
            .Scriptdataescapedendtagname => {},
            .Scriptdatadoubleescapestart => {},
            .Scriptdatadoubleescaped => {},
            .Scriptdatadoubleescapeddash => {},
            .Scriptdatadoubleescapeddashdash => {},
            .Scriptdatadoubleescapedlessthansign => {},
            .Scriptdatadoubleescapeend => {},
            .Beforeattributename => {},
            .Attributename => {},
            .Afterattributename => {},
            .Beforeattributevalue => {},
            .Attributevaluedoublequoted => {},
            .Attributevaluesinglequoted => {},
            .Attributevalueunquoted => {},
            .Afterattributevaluequoted => {},
            .Selfclosingstarttag => {},
            .Boguscomment => {},
            .Markupdeclarationopen => {},
            .Commentstart => {},
            .Commentstartdash => {},
            .Comment => {},
            .Commentlessthansign => {},
            .Commentlessthansignbang => {},
            .Commentlessthansignbangdash => {},
            .Commentlessthansignbangdashdash => {},
            .Commentenddash => {},
            .Commentend => {},
            .Commentendbang => {},
            .DOCTYPE => {},
            .BeforeDOCTYPEname => {},
            .DOCTYPEname => {},
            .AfterDOCTYPEname => {},
            .AfterDOCTYPEpublickeyword => {},
            .BeforeDOCTYPEpublicidentifier => {},
            .DOCTYPEpublicidentifierdoublequoted => {},
            .DOCTYPEpublicidentifiersinglequoted => {},
            .AfterDOCTYPEpublicidentifier => {},
            .BetweenDOCTYPEpublicandsystemidentifiers => {},
            .AfterDOCTYPEsystemkeyword => {},
            .BeforeDOCTYPEsystemidentifier => {},
            .DOCTYPEsystemidentifierdoublequoted => {},
            .DOCTYPEsystemidentifiersinglequoted => {},
            .AfterDOCTYPEsystemidentifier => {},
            .BogusDOCTYPE => {},
            .CDATAsection => {},
            .CDATAsectionbracket => {},
            .CDATAsectionend => {},
            .Characterreference => {},
            .Namedcharacterreference => {},
            .Ambiguousampersand => {},
            .Numericcharacterreference => {},
            .Hexadecimalcharacterreferencestart => {},
            .Decimalcharacterreferencestart => {},
            .Hexadecimalcharacterreference => {},
            .Decimalcharacterreference => {},
            .Numericcharacterreferenceend => {},
        }
    }
};
